"""add daily digests

Revision ID: 2743c7326799
Revises: e43c35127509
Create Date: 2026-09-18 16:48:33.089407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2743c7326799'
down_revision: Union[str, Sequence[str], None] = 'e43c35127509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_digests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('digest_date', sa.Date(), nullable=False),
    sa.Column('total_emails', sa.Integer(), nullable=False),
    sa.Column('important_emails', sa.Integer(), nullable=False),
    sa.Column('emails', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_digests_digest_date'), 'daily_digests', ['digest_date'], unique=False)
    op.create_index(op.f('ix_daily_digests_id'), 'daily_digests', ['id'], unique=False)
    op.create_index(op.f('ix_daily_digests_user_id'), 'daily_digests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_digests_user_id'), table_name='daily_digests')
    op.drop_index(op.f('ix_daily_digests_id'), table_name='daily_digests')
    op.drop_index(op.f('ix_daily_digests_digest_date'), table_name='daily_digests')
    op.drop_table('daily_digests')
    # ### end Alembic commands ###
