"""update email_analyses jsonb columns

Revision ID: 7bba325869bf
Revises: 84b318512546
Create Date: 2026-09-18 15:52:49.098878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bba325869bf'
down_revision: Union[str, Sequence[str], None] = '84b318512546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_analyses', sa.Column('category', sa.String(length=50), nullable=False))
    op.alter_column('email_analyses', 'language',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('email_analyses', 'actions',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using="actions::jsonb",
               existing_nullable=False)
    op.alter_column('email_analyses', 'deadlines',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using="deadlines::jsonb",
               existing_nullable=False)
    op.drop_constraint(op.f('email_analyses_email_id_key'), 'email_analyses', type_='unique')
    op.create_index(op.f('ix_email_analyses_email_id'), 'email_analyses', ['email_id'], unique=True)
    op.create_index(op.f('ix_email_analyses_id'), 'email_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_analyses_id'), table_name='email_analyses')
    op.drop_index(op.f('ix_email_analyses_email_id'), table_name='email_analyses')
    op.create_unique_constraint(op.f('email_analyses_email_id_key'), 'email_analyses', ['email_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('email_analyses', 'deadlines',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               postgresql_using="deadlines::text",
               existing_nullable=False)
    op.alter_column('email_analyses', 'actions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               postgresql_using="actions::text",
               existing_nullable=False)
    op.alter_column('email_analyses', 'language',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('email_analyses', 'category')
    # ### end Alembic commands ###
