"""add email analyses

Revision ID: 84b318512546
Revises: 82bd4d978edd
Create Date: 2026-09-18 11:41:05.925586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84b318512546'
down_revision: Union[str, Sequence[str], None] = '82bd4d978edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_analyses', 'actions',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('email_analyses', 'deadlines',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_analyses', 'deadlines',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('email_analyses', 'actions',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
